name: Build Android Debug (manual)

on:
  workflow_dispatch:

jobs:
  android-debug:
    runs-on: ubuntu-latest

    env:
      NODE_OPTIONS: --max_old_space_size=4096
      GRADLE_USER_HOME: ${{ github.workspace }}/.gradle
      YARN_NODE_LINKER: node-modules  # 双保险

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (20.x)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack & Yarn 4.2.2
        run: |
          corepack enable
          corepack prepare yarn@4.2.2 --activate
          yarn --version

      - name: Install deps (node-modules linker)
        run: |
          yarn config set nodeLinker node-modules
          yarn install --mode=update-lockfile
          node -v
          yarn -v

      # 诊断：列出关键目录；兜底：缺啥补啥（只装到 runner）
      - name: Ensure Android RN CLI + Gradle plugin present
        run: |
          set -e
          echo "== Diagnostics =="
          ls -la node_modules | head -n 50 || true
          ls -la node_modules/@react-native-community || true
          ls -la node_modules/@react-native || true

          NEED_FIX=0
          if [ ! -f "node_modules/@react-native-community/cli-platform-android/native_modules.gradle" ]; then
            echo "Missing @react-native-community/cli-platform-android/native_modules.gradle — installing..."
            yarn add -D @react-native-community/cli-platform-android
            NEED_FIX=1
          fi

          if [ ! -d "node_modules/@react-native/gradle-plugin" ]; then
            echo "Missing @react-native/gradle-plugin — installing..."
            yarn add -D @react-native/gradle-plugin
            NEED_FIX=1
          fi

          if [ "$NEED_FIX" = "1" ]; then
            echo "Rechecking after install..."
            test -f node_modules/@react-native-community/cli-platform-android/native_modules.gradle
            test -d node_modules/@react-native/gradle-plugin
          fi

      - name: Setup Java (Temurin 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build Debug APK
        working-directory: android
        run: ./gradlew :app:assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: xstreaming-android-debug-apk
          path: android/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
          retention-days: 7
