name: Android CI (React Native 0.72.14) - Debug no Metro

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  build-android-debug:
    name: Build Android Debug APK (no Metro)
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Corepack & Yarn 4.2.2
        run: |
          corepack enable
          corepack prepare yarn@4.2.2 --activate

      # 允许在 CI 中更新缓存/锁（避免 immutable 报错）
      - name: Install dependencies
        run: yarn install --no-immutable

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      # RN 0.72 / AGP 8 需要 JDK 17
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Gradle (cache)
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      # （可选）使用“自定义 debug keystore”
      # 若未提供 DEBUG_KEYSTORE_BASE64，则使用系统默认 ~/.android/debug.keystore
      - name: Decode custom debug keystore (optional)
        run: |
          if [ -n "${{ secrets.DEBUG_KEYSTORE_BASE64 }}" ]; then
            echo "${{ secrets.DEBUG_KEYSTORE_BASE64 }}" | base64 -d > android/app/debug.keystore
            echo "Decoded custom debug keystore to android/app/debug.keystore"
          else
            echo "No DEBUG_KEYSTORE_BASE64 provided. Will use default ~/.android/debug.keystore"
          fi

      # （可选）注入自定义 debug keystore 的密码/别名
      - name: Export debug signing env (optional)
        run: |
          echo "DEBUG_STORE_PASSWORD=${{ secrets.DEBUG_STORE_PASSWORD }}" >> $GITHUB_ENV
          echo "DEBUG_KEY_ALIAS=${{ secrets.DEBUG_KEY_ALIAS }}"         >> $GITHUB_ENV
          echo "DEBUG_KEY_PASSWORD=${{ secrets.DEBUG_KEY_PASSWORD }}"   >> $GITHUB_ENV

      # 关键：不再手动 bundle，由 Gradle 的 bundleInDebug 自动完成
      - name: Build APK (assembleDebug)
        working-directory: android
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
