name: Build Android Debug (manual, apply patches)

on:
  workflow_dispatch:

jobs:
  android-debug:
    runs-on: ubuntu-latest

    env:
      NODE_OPTIONS: --max_old_space_size=4096
      GRADLE_USER_HOME: ${{ github.workspace }}/.gradle
      YARN_NODE_LINKER: node-modules  # 双保险，强制用 node-modules

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (20.x)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack & Yarn 4.2.2
        run: |
          corepack enable
          corepack prepare yarn@4.2.2 --activate
          yarn --version

      # 1) 规范化补丁换行（CRLF -> LF）
      - name: Normalize patch files (CRLF -> LF)
        run: |
          if [ -d patches ]; then
            find patches -type f -name "*.patch" -print0 | xargs -0 -I{} bash -lc 'sed -i "s/\r$//" "{}"'
          fi

      # 2) 安装依赖：使用 node-modules 链接器，并跳过 lifecycle scripts（避免 patch-package 在此阶段运行）
      - name: Install dependencies (skip scripts)
        run: |
          yarn config set nodeLinker node-modules
          YARN_ENABLE_SCRIPTS=false yarn install --mode=update-lockfile
          node -v
          yarn -v

      # 3) 手动应用补丁（此时补丁已为 LF）
      - name: Apply patch-package patches
        run: npx patch-package

      # 4) 兜底：确保 RN Android CLI & Gradle plugin 存在（仅对 runner 生效）
      - name: Ensure RN Android CLI & Gradle plugin
        run: |
          set -e
          MISSING=0
          if [ ! -f "node_modules/@react-native-community/cli-platform-android/native_modules.gradle" ]; then
            echo "Missing native_modules.gradle — installing @react-native-community/cli-platform-android ..."
            YARN_ENABLE_SCRIPTS=false yarn add -D @react-native-community/cli-platform-android
            MISSING=1
          fi
          if [ ! -d "node_modules/@react-native/gradle-plugin" ]; then
            echo "Missing @react-native/gradle-plugin — installing ..."
            YARN_ENABLE_SCRIPTS=false yarn add -D @react-native/gradle-plugin
            MISSING=1
          fi
          if [ "$MISSING" = "1" ]; then
            # 再跑一次 patch-package，确保新增包也应用到补丁（若有）
            npx patch-package || true
          fi
          # 最终强校验
          test -f node_modules/@react-native-community/cli-platform-android/native_modules.gradle
          test -d node_modules/@react-native/gradle-plugin

      - name: Setup Java (Temurin 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build Debug APK
        working-directory: android
        run: ./gradlew :app:assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: xstreaming-android-debug-apk
          path: android/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
          retention-days: 7
